### ISSUE TITLE
Я тут был

### ISSUE THREAD

**Issue by limitedeternity** [lex-js/lex-js#1]
https://github.com/limitedeternity/lex-js

**Comment by klntsky** [comment]
@limitedeternity, годно, наверное (пока не запускал). Интересно, зачем кому-то ещё понадобилось работать с файлами в этом формате.

> Исправления ошибок

Буду благодарен за их список.

**Comment by klntsky** [comment]
`bundle.min.js` без сорцев - это не ОК.
Нужно переделать, чтобы собиралось из исходников.

И да, стартпейдж-то поломался:

![2019-02-22-213036_962x114_scrot](https://user-images.githubusercontent.com/18447310/53262970-222a7b00-36e9-11e9-8bfd-7804d8f6fe74.png)

А всё потому, что 
```
$ file sample/info.txt
sample/info.txt: ISO-8859 text, with CRLF line terminators
$ file public/startPage/info.txt
public/startPage/info.txt: ISO-8859 text

```

**Comment by limitedeternity** [comment]
Синтаксическая ошибка в стилях (точка с запятой вместо двоеточия, с подсветкой её сразу можно увидеть) не дает подключиться остальному куску CSS.
Остальное некритично, ибо заключается в неявности некоторых моментов (вроде того, что всё плывет, когда передаешь время изменения файла в миллисекундах).
Было бы неплохо, если бы в конфигах можно было оверрайднуть директорию, из которой подгружаются иконки при запуске "файлового менеджера".

**Comment by limitedeternity** [comment]
>with CRLF line terminators

Видел, но руки не дошли до исправления ситуации

**Comment by limitedeternity** [comment]
>Интересно, зачем кому-то ещё понадобилось работать с файлами в этом формате.

Привет из Герцена.

**Comment by limitedeternity** [comment]
>Нужно переделать, чтобы собиралось из исходников.

И каким образом оно собирается?

**Comment by klntsky** [comment]
> Синтаксическая ошибка в стилях

Ага, спасибо.

Да, можно объединить, давай сделаем.

Код на PHP убирать нет смысла, нет проблемы в том, чтобы иметь два бэкэнда, если у них общее API. PHP был изначально выбран т.к. нищехостинги его предоставляют чаще, чем ноду, что увеличивает доступность для не программирующих людей.

> И каким образом оно собирается?

`npm install && npx grunt`

У тебя в tg ник такой же?

**Comment by limitedeternity** [comment]
Да, такой же. А directory traversal сейчас закрою.
